import type { CollectionEntry } from 'astro:content';

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
  'should', 'may', 'might', 'can', 'this', 'that', 'these', 'those',
  'it', 'its', 'i', 'you', 'we', 'they', 'he', 'she', 'so', 'as',
  'if', 'not', 'no', 'from', 'into', 'about', 'just', 'more', 'than',
  'very', 'also', 'all', 'each', 'every', 'both', 'few', 'other',
  'some', 'such', 'only', 'own', 'same', 'too', 'much', 'which',
  'who', 'whom', 'what', 'when', 'where', 'how', 'why', 'here',
  'there', 'then', 'therefore', 'thus', 'hence', 'while', 'during',
  'before', 'after', 'since', 'until', 'unless', 'however', 'although',
  'though', 'even', 'still', 'yet', 'upon', 'over', 'under', 'above',
  'below', 'between', 'among', 'within', 'without', 'through', 'across',
  'along', 'against', 'despite', 'beyond', 'toward', 'towards',
  'because', 'whether', 'whereas', 'wherever', 'whenever', 'whatever',
  'whoever', 'whichever', 'one', 'two', 'three', 'four', 'five',
  'six', 'seven', 'eight', 'nine', 'ten', 'first', 'second', 'third',
  'next', 'last', 'any', 'many', 'several', 'most', 'fewer', 'less',
  'make', 'makes', 'made', 'use', 'used', 'using', 'get', 'gets',
  'got', 'go', 'goes', 'went', 'going', 'take', 'takes', 'took',
  'taken', 'come', 'comes', 'came', 'coming', 'see', 'sees', 'saw',
  'seen', 'know', 'knows', 'knew', 'known', 'think', 'thinks',
  'thought', 'want', 'wants', 'wanted', 'give', 'gives', 'gave',
  'given', 'tell', 'tells', 'told', 'find', 'finds', 'found',
  'need', 'needs', 'needed', 'feel', 'feels', 'felt', 'try', 'tries',
  'tried', 'work', 'works', 'worked', 'call', 'calls', 'called',
  'like', 'likes', 'liked', 'put', 'puts', 'mean', 'means', 'meant',
  'keep', 'keeps', 'kept', 'let', 'lets', 'begin', 'begins', 'began',
  'begun', 'seem', 'seems', 'seemed', 'help', 'helps', 'helped',
  'show', 'shows', 'showed', 'shown', 'hear', 'hears', 'heard',
  'play', 'plays', 'played', 'run', 'runs', 'ran', 'move', 'moves',
  'moved', 'live', 'lives', 'lived', 'bring', 'brings', 'brought',
  'happen', 'happens', 'happened', 'write', 'writes', 'wrote',
  'written', 'provide', 'provides', 'provided', 'sit', 'sits', 'sat',
  'stand', 'stands', 'stood', 'lose', 'loses', 'lost', 'pay', 'pays',
  'paid', 'meet', 'meets', 'met', 'include', 'includes', 'included',
  'continue', 'continues', 'continued', 'set', 'sets', 'learn',
  'learns', 'learned', 'learnt', 'change', 'changes', 'changed',
  'lead', 'leads', 'led', 'understand', 'understands', 'understood',
  'watch', 'watches', 'watched', 'follow', 'follows', 'followed',
  'stop', 'stops', 'stopped', 'create', 'creates', 'created',
  'speak', 'speaks', 'spoke', 'spoken', 'read', 'reads', 'allow',
  'allows', 'allowed', 'add', 'adds', 'added', 'spend', 'spends',
  'spent', 'grow', 'grows', 'grew', 'grown', 'open', 'opens',
  'opened', 'walk', 'walks', 'walked', 'win', 'wins', 'won',
  'offer', 'offers', 'offered', 'remember', 'remembers', 'remembered',
  'love', 'loves', 'loved', 'consider', 'considers', 'considered',
  'appear', 'appears', 'appeared', 'buy', 'buys', 'bought',
  'wait', 'waited', 'serve', 'serves', 'served', 'die', 'dies',
  'died', 'send', 'sends', 'sent', 'expect', 'expects', 'expected',
  'build', 'builds', 'built', 'stay', 'stays', 'stayed', 'fall',
  'falls', 'fell', 'fallen', 'cut', 'cuts', 'reach', 'reaches',
  'reached', 'kill', 'kills', 'killed', 'remain', 'remains',
  'remained', 'suggest', 'suggests', 'suggested', 'raise', 'raises',
  'raised', 'pass', 'passes', 'passed', 'sell', 'sells', 'sold',
  'require', 'requires', 'required', 'report', 'reports', 'reported',
  'decide', 'decides', 'decided', 'pull', 'pulls', 'pulled',
  'return', 'returns', 'returned', 'explain', 'explains', 'explained',
  'develop', 'develops', 'developed', 'hope', 'hopes', 'hoped',
  'receive', 'receives', 'received', 'agree', 'agrees', 'agreed',
  'support', 'supports', 'supported', 'manage', 'manages', 'managed',
  'carry', 'carries', 'carried', 'accept', 'accepts', 'accepted',
  'break', 'breaks', 'broke', 'broken', 'pick', 'picks', 'picked',
  'hit', 'hits', 'wear', 'wears', 'wore', 'worn', 'lay', 'lays',
  'laid', 'hang', 'hangs', 'hung', 'seek', 'seeks', 'sought',
  'throw', 'throws', 'threw', 'thrown', 'catch', 'catches', 'caught',
  'drive', 'drives', 'drove', 'driven', 'shake', 'shakes', 'shook',
  'shaken', 'ride', 'rides', 'rode', 'ridden', 'blow', 'blows',
  'blew', 'blown', 'eat', 'eats', 'ate', 'eaten', 'choose',
  'chooses', 'chose', 'chosen', 'swim', 'swims', 'swam', 'swum',
  'fly', 'flies', 'flew', 'flown', 'hide', 'hides', 'hid', 'hidden',
  'sleep', 'sleeps', 'slept', 'teach', 'teaches', 'taught', 'wake',
  'wakes', 'woke', 'woken', 'ring', 'rings', 'rang', 'rung',
  'sing', 'sings', 'sang', 'sung', 'swing', 'swings', 'swung',
  'drink', 'drinks', 'drank', 'drunk', 'draw', 'draws', 'drew',
  'drawn', 'feed', 'feeds', 'fed', 'fight', 'fights', 'fought',
  'forbid', 'forbids', 'forbade', 'forbidden', 'forget', 'forgets',
  'forgot', 'forgotten', 'forgive', 'forgives', 'forgave', 'forgiven',
  'freeze', 'freezes', 'froze', 'frozen', 'gotten', 'hold', 'holds',
  'held', 'hurt', 'hurts', 'lend', 'lends', 'lent', 'lie', 'lies',
  'lay', 'lain', 'light', 'lights', 'lit', 'lost', 'mean', 'means',
  'meant', 'met', 'raise', 'raises', 'raised', 'realize', 'realizes',
  'realized', 'recall', 'recalls', 'recalled', 'recognize', 'recognizes',
  'recognized', 'reflect', 'reflects', 'reflected', 'regard', 'regards',
  'regarded', 'regret', 'regrets', 'regretted', 'relate', 'relates',
  'related', 'relax', 'relaxes', 'relaxed', 'release', 'releases',
  'released', 'relieve', 'relieves', 'relieved', 'rely', 'relies',
  'relied', 'remain', 'remains', 'remained', 'remark', 'remarks',
  'remarked', 'remind', 'reminds', 'reminded', 'remove', 'removes',
  'removed', 'repeat', 'repeats', 'repeated', 'replace', 'replaces',
  'replaced', 'reply', 'replies', 'replied', 'report', 'reports',
  'reported', 'represent', 'represents', 'represented', 'request',
  'requests', 'requested', 'require', 'requires', 'required',
  'rescue', 'rescues', 'rescued', 'research', 'researches', 'researched',
  'resign', 'resigns', 'resigned', 'resist', 'resists', 'resisted',
  'resolve', 'resolves', 'resolved', 'respect', 'respects', 'respected',
  'rest', 'rests', 'rested', 'restore', 'restores', 'restored',
  'restrict', 'restricts', 'restricted', 'result', 'results',
  'resulted', 'retain', 'retains', 'retained', 'return', 'returns',
  'returned', 'reveal', 'reveals', 'revealed', 'reverse', 'reverses',
  'reversed', 'review', 'reviews', 'reviewed', 'reward', 'rewards',
  'rewarded', 'rhythm', 'rid', 'ride', 'rides', 'rode', 'ridden',
  'ridge', 'rifle', 'right', 'rights', 'ring', 'rings', 'rang',
  'rung', 'risk', 'risks', 'rise', 'rises', 'rose', 'risen',
  'ritual', 'river', 'road', 'roads', 'rob', 'robs', 'robbed',
  'rock', 'rocks', 'rocket', 'rockets', 'rod', 'role', 'roles',
  'roll', 'rolls', 'rolled', 'romantic', 'roof', 'roofs',
  'room', 'rooms', 'root', 'roots', 'rope', 'ropes', 'rose',
  'roses', 'rotate', 'rotates', 'rotated', 'rough', 'round',
  'rounds', 'route', 'routes', 'routine', 'routines', 'row',
  'rows', 'rub', 'rubs', 'rubbed', 'rubber', 'rug', 'rugs',
  'ruin', 'ruins', 'ruined', 'rule', 'rules', 'ruled',
  'ruler', 'rulers', 'rumor', 'rumors', 'run', 'runs', 'ran',
  'runner', 'runners', 'rural', 'rush', 'rushes', 'rushed',
  'sad', 'sacred', 'sacrifice', 'sacrifices', 'sacrificed',
  'safe', 'safely', 'safety', 'sake', 'salad', 'salads',
  'salary', 'sale', 'sales', 'salt', 'same', 'sample',
  'samples', 'sand', 'sandwich', 'sandwiches', 'sat',
  'satellite', 'satellites', 'satisfaction', 'satisfy', 'satisfies',
  'satisfied', 'saturday', 'sauce', 'saucer', 'saucers', 'saved',
  'savings', 'say', 'says', 'said', 'scale', 'scales',
  'scandal', 'scandals', 'scene', 'scenes', 'scent', 'scents',
  'schedule', 'schedules', 'scheme', 'schemes', 'school', 'schools',
  'science', 'sciences', 'scope', 'scorched', 'score', 'scores',
  'scored', 'scorned', 'scout', 'scouts', 'scrape', 'scrapes',
  'scraped', 'screen', 'screens', 'screw', 'screws', 'script',
  'scripts', 'scroll', 'scrolls', 'sea', 'seal', 'seals',
  'seam', 'seams', 'search', 'searches', 'searched', 'seaside',
  'seat', 'seats', 'second', 'seconds', 'secret', 'secrets',
  'secretary', 'sect', 'sects', 'sector', 'sectors', 'secular',
  'secure', 'secures', 'secured', 'security', 'see', 'sees',
  'seed', 'seeds', 'seek', 'seeks', 'sought', 'seem', 'seems',
  'seemed', 'semen', 'senate', 'senator', 'senators', 'send',
  'sends', 'sent', 'senior', 'seniors', 'sense', 'senses',
  'sensitive', 'sentence', 'sentences', 'sentiment', 'sentiments',
  'separate', 'separates', 'separated', 'september', 'sequence',
  'sequences', 'serene', 'serious', 'servant', 'servants',
  'serve', 'serves', 'served', 'service', 'services',
  'session', 'sessions', 'set', 'sets', 'setting', 'settings',
  'settle', 'settles', 'settled', 'seven', 'several', 'severe',
  'sewage', 'sewer', 'sewers', 'sex', 'sexual', 'shade',
  'shades', 'shadow', 'shadows', 'shaft', 'shafts', 'shake',
  'shakes', 'shook', 'shaken', 'shall', 'shame', 'shames',
  'shape', 'shapes', 'shaped', 'share', 'shares', 'shared',
  'sharp', 'shave', 'shaves', 'shaved', 'she', 'shed',
  'sheds', 'shedding', 'sheep', 'sheet', 'sheets', 'shelf',
  'shell', 'shells', 'shelter', 'shelters', 'shift', 'shifts',
  'shifted', 'shine', 'shines', 'shined', 'ship', 'ships',
  'shirt', 'shirts', 'shock', 'shocks', 'shocked', 'shoe',
  'shoes', 'shop', 'shops', 'shopping', 'shore', 'shores',
  'short', 'shortly', 'shorts', 'shot', 'shots', 'should',
  'shoulder', 'shoulders', 'shout', 'shouts', 'shouted', 'show',
  'shows', 'showed', 'shown', 'shower', 'showers', 'shrimp',
  'shrine', 'shrines', 'shrub', 'shrubs', 'shrug', 'shrugs',
  'shrugged', 'shut', 'shuts', 'shy', 'sick', 'side',
  'sides', 'siege', 'sieges', 'sight', 'sights', 'sign',
  'signs', 'signed', 'signal', 'signals', 'silence', 'silences',
  'silent', 'silk', 'silver', 'similar', 'simple', 'simply',
  'simulate', 'simulates', 'simulated', 'sin', 'since', 'sing',
  'sings', 'sang', 'sung', 'single', 'singles', 'sink',
  'sinks', 'sank', 'sunk', 'sir', 'sister', 'sisters',
  'sit', 'sits', 'sat', 'site', 'sites', 'situated',
  'situation', 'situations', 'six', 'sixth', 'size', 'sizes',
  'ski', 'skies', 'skill', 'skills', 'skin', 'skins',
  'skirt', 'skirts', 'skull', 'skulls', 'sky', 'skyscraper',
  'skyscrapers', 'slam', 'slams', 'slammed', 'slap', 'slaps',
  'slapped', 'slave', 'slaves', 'sleep', 'sleeps', 'slept',
  'slice', 'slices', 'sliced', 'slide', 'slides', 'slid',
  'slight', 'slightly', 'slim', 'slip', 'slips', 'slipped',
  'slit', 'slits', 'slopes', 'slow', 'slowly', 'slugs',
  'small', 'smart', 'smell', 'smells', 'smelled', 'smile',
  'smiles', 'smiled', 'smoke', 'smokes', 'smoked', 'smooth',
  'snake', 'snakes', 'snap', 'snaps', 'snapped', 'snow',
  'snows', 'snowy', 'so', 'soak', 'soaks', 'soaked',
  'soap', 'soaps', 'sober', 'soccer', 'social', 'society',
  'sock', 'socks', 'soda', 'soft', 'softly', 'software',
  'soil', 'sold', 'solar', 'soldier', 'soldiers', 'sole',
  'solely', 'solemn', 'some', 'someone', 'something', 'sometimes',
  'somewhat', 'somewhere', 'son', 'sons', 'soon', 'sophisticated',
  'sorry', 'sort', 'sorts', 'sorted', 'soul', 'souls',
  'sound', 'sounds', 'source', 'sources', 'south', 'southern',
  'space', 'spaces', 'span', 'spans', 'spare', 'spares',
  'spared', 'spark', 'sparks', 'sparkled', 'sparrow', 'sparrows',
  'spat', 'spawn', 'spawns', 'spawned', 'speaker', 'speakers',
  'special', 'specialty', 'species', 'specific', 'specifically',
  'specified', 'specify', 'specifies', 'specified', 'specimen', 'specimens',
  'speed', 'speeds', 'spell', 'spells', 'spelled', 'spelling',
  'spend', 'spends', 'spent', 'sphere', 'spheres', 'spice',
  'spices', 'spicy', 'spider', 'spiders', 'spill', 'spills',
  'spilled', 'spin', 'spins', 'spun', 'spirit', 'spirits',
  'spiritual', 'spit', 'spits', 'splendid', 'split', 'splits',
  'split', 'spoke', 'spoken', 'sponsor', 'sponsors', 'sponsored',
  'spontaneous', 'spoon', 'spoons', 'sport', 'sports', 'spot',
  'spots', 'spotted', 'spray', 'sprays', 'sprayed', 'spread',
  'spreads', 'spread', 'spring', 'springs', 'sprung', 'sprinkle',
  'sprinkles', 'sprinkled', 'squirrel', 'squirrels', 'stab', 'stabs',
  'stabbed', 'stable', 'stack', 'stacks', 'stacked', 'stadium',
  'stadiums', 'staff', 'staffs', 'stage', 'stages', 'staged',
  'stain', 'stains', 'stained', 'stair', 'stairs', 'stake',
  'stakes', 'stale', 'stall', 'stalls', 'stalled', 'stamp',
  'stamps', 'stamped', 'stance', 'stances', 'stand', 'stands',
  'stood', 'standard', 'standards', 'standing', 'stank', 'stanza',
  'stanzas', 'stare', 'stares', 'stared', 'star', 'stars',
  'started', 'start', 'starts', 'started', 'starve', 'starves',
  'starved', 'stash', 'stashes', 'stashed', 'stat', 'stats',
  'state', 'states', 'stated', 'statement', 'statements',
  'static', 'station', 'stations', 'statistic', 'statistics',
  'statue', 'statues', 'status', 'statuses', 'stays', 'stayed',
  'steadily', 'steady', 'steak', 'steaks', 'steal', 'steals',
  'stole', 'stolen', 'steam', 'steams', 'steel', 'steep',
  'steer', 'steers', 'steered', 'stem', 'stems', 'step',
  'steps', 'stepped', 'stereo', 'stereotype', 'stereotypes', 'stern',
  'stew', 'sticks', 'stuck', 'stick', 'sticks', 'stuck',
  'stiff', 'stiffness', 'still', 'sting', 'stings', 'stung',
  'stink', 'stinks', 'stank', 'stunk', 'stir', 'stirs',
  'stirred', 'stitch', 'stitches', 'stitched', 'stock', 'stocks',
  'stocked', 'stole', 'stomach', 'stomachs', 'stone', 'stones',
  'stood', 'stool', 'stools', 'stop', 'stops', 'stopped',
  'storage', 'store', 'stores', 'stored', 'storm', 'storms',
  'story', 'stories', 'stove', 'stoves', 'stove', 'stoves',
  'straight', 'strain', 'strains', 'strained', 'strait', 'straits',
  'strand', 'strands', 'stranded', 'strange', 'stranger', 'strangers',
  'strap', 'straps', 'strapped', 'straw', 'strawberry', 'strawberries',
  'stray', 'strays', 'stream', 'streams', 'streamed', 'street',
  'streets', 'strength', 'strengths', 'strengthen', 'strengthens', 'strengthened',
  'stress', 'stresses', 'stressed', 'stretch', 'stretches', 'stretched',
  'strict', 'stride', 'strides', 'strode', 'stride', 'strides',
  'struck', 'strike', 'strikes', 'struck', 'stricken', 'string',
  'strings', 'strip', 'strips', 'stripped', 'stripe', 'stripes',
  'stroke', 'strokes', 'stroked', 'stroll', 'strolls', 'strolled',
  'strong', 'strongly', 'structure', 'structures', 'structured',
  'struggle', 'struggles', 'struggled', 'strut', 'struts', 'strutted',
  'stubborn', 'stuck', 'stud', 'studs', 'student', 'students',
  'studied', 'studies', 'study', 'studies', 'studied', 'stuff',
  'stuffs', 'stuffed', 'stumble', 'stumbles', 'stumbled', 'stump',
  'stumps', 'stumped', 'stunning', 'stunt', 'stunts', 'stunted',
  'stupid', 'sturdy', 'style', 'styles', 'styled', 'stylus',
  'styluses', 'sub', 'subs', 'subject', 'subjects', 'sublime',
  'submit', 'submits', 'submitted', 'substantial', 'substance', 'substances',
  'substitute', 'substitutes', 'substituted', 'subtle', 'subtly', 'suburb',
  'suburbs', 'success', 'successful', 'suck', 'sucks', 'sucked',
  'sudden', 'suddenly', 'suffer', 'suffers', 'suffered', 'sufficient',
  'sugar', 'suggest', 'suggests', 'suggested', 'suit', 'suits',
  'suite', 'suites', 'suited', 'sulfur', 'sulk', 'sulks',
  'sulked', 'sullen', 'sultan', 'sultans', 'sum', 'sums',
  'summer', 'summers', 'summit', 'summits', 'summon', 'summons',
  'summoned', 'sump', 'sumps', 'sumptuous', 'sun', 'sunbeam',
  'sunbeams', 'sunburn', 'sunburns', 'sunday', 'sundays', 'sundial',
  'sundials', 'sundown', 'sundries', 'sundial', 'sundials', 'sunflower',
  'sunflowers', 'sung', 'sunglasses', 'sunk', 'sunken', 'sunny',
  'sunrise', 'sunrises', 'sunset', 'sunsets', 'sunshine', 'sunspot',
  'sunspots', 'super', 'superb', 'superhuman', 'superior', 'superiority',
  'superman', 'supermarket', 'supermarkets', 'supernatural', 'supersede', 'supersedes',
  'superseded', 'supervise', 'supervises', 'supervised', 'supper', 'supplies',
  'supply', 'supplies', 'supplied', 'support', 'supports', 'supported',
  'suppose', 'supposes', 'supposed', 'suppression', 'suppress', 'suppresses',
  'suppressed', 'supreme', 'surgery', 'surge', 'surges', 'surged',
  'surgeon', 'surgeons', 'surgeon', 'surgeons', 'surgeon', 'surgeons',
  'surges', 'surged', 'surging', 'surgical', 'surmise', 'surmises',
  'surmised', 'surname', 'surnames', 'surpass', 'surpasses', 'surpassed',
  'surplus', 'surplus', 'surprise', 'surprises', 'surprised', 'surreal',
  'surrender', 'surrenders', 'surrendered', 'surround', 'surrounds', 'surrounded',
  'survey', 'surveys', 'surveyed', 'survival', 'survive', 'survives',
  'survived', 'survivor', 'survivors', 'suspect', 'suspects', 'suspected',
  'suspend', 'suspends', 'suspended', 'suspicion', 'suspicions', 'suspicious',
  'sustain', 'sustains', 'sustained', 'swab', 'swabs', 'swabbed',
  'swallow', 'swallows', 'swallowed', 'swam', 'swamp', 'swamps',
  'swamped', 'swan', 'swans', 'swap', 'swaps', 'swapped',
  'swarm', 'swarms', 'swarmed', 'swath', 'swaths', 'sway',
  'sways', 'swayed', 'swear', 'swears', 'swore', 'sworn',
  'sweat', 'sweats', 'sweated', 'sweep', 'sweeps', 'swept',
  'sweet', 'sweetly', 'sweets', 'swell', 'swells', 'swelled',
  'swelled', 'swept', 'swift', 'swiftly', 'swimmer', 'swimmers',
  'swimming', 'swim', 'swims', 'swam', 'swum', 'swine',
  'swine', 'swing', 'swings', 'swung', 'swipe', 'swipes',
  'swiped', 'swirl', 'swirls', 'swirled', 'switch', 'switches',
  'switched', 'sword', 'swords', 'swordsman', 'swordsmen', 'swore',
  'sworn', 'swum', 'syllable', 'syllables', 'symbol', 'symbols',
  'symbolic', 'symbolize', 'symbolizes', 'symbolized', 'symmetry', 'sympathy',
  'symphony', 'symphonies', 'symptom', 'symptoms', 'sync', 'syncs',
  'synchronized', 'syndrome', 'syndromes', 'synergy', 'syphon', 'syphons',
  'syphon', 'syphons', 'syringe', 'syringes', 'system', 'systems',
  'systematic', 'systematically', 'table', 'tables', 'tablet', 'tablets',
  'tablespoon', 'tablespoons', 'tachometer', 'tachometers', 'tacit', 'tack',
  'tacks', 'tacked', 'tackle', 'tackles', 'tackled', 'tacky',
  'tact', 'tactic', 'tactics', 'tactile', 'tactless', 'tadpole',
  'tadpoles', 'tag', 'tags', 'tagged', 'tail', 'tails',
  'tailed', 'tailor', 'tailors', 'tailored', 'tailwind', 'tails',
  'taint', 'taints', 'tainted', 'take', 'takes', 'took',
  'taken', 'tale', 'tales', 'talent', 'talents', 'talk',
  'talks', 'talked', 'tall', 'tally', 'tallies', 'tally',
  'tallies', 'tame', 'tames', 'tamed', 'tan', 'tans',
  'tanned', 'tank', 'tanks', 'tanker', 'tankers', 'tanned',
  'tanner', 'tanners', 'tap', 'taps', 'tapped', 'tape',
  'tapes', 'taped', 'taper', 'tapers', 'tapered', 'tapestry',
  'tapestries', 'tar', 'tars', 'tared', 'tarnish', 'tarnishes',
  'tarnished', 'tariff', 'tariffs', 'task', 'tasks', 'tasked',
  'taste', 'tastes', 'tasted', 'tat', 'tats', 'tattered',
  'tattoo', 'tattoos', 'tattooed', 'taught', 'taunt', 'taunts',
  'taunted', 'tax', 'taxes', 'taxed', 'taxing', 'taxman',
  'taxmen', 'tea', 'teach', 'teaches', 'taught', 'teacher',
  'teachers', 'teaching', 'teachings', 'team', 'teams', 'teamed',
  'tear', 'tears', 'tore', 'torn', 'teaspoon', 'teaspoons',
  'teaspoon', 'teaspoons', 'teaspoon', 'teaspoons', 'technical', 'technically',
  'technician', 'technicians', 'technique', 'techniques', 'technology', 'tedious',
  'tee', 'tees', 'teeth', 'teeth', 'telegram', 'telegrams',
  'telegraph', 'telegraphs', 'television', 'televisions', 'tell', 'tells',
  'told', 'temper', 'tempers', 'tempered', 'temperature', 'temperatures',
  'temple', 'temples', 'temporal', 'temporary', 'tempt', 'tempts',
  'tempted', 'temptation', 'temptations', 'ten', 'tenant', 'tenants',
  'tend', 'tends', 'tended', 'tender', 'tenders', 'tendered',
  'tenement', 'tenements', 'tennis', 'tenor', 'tenors', 'tense',
  'tenses', 'tensed', 'tent', 'tents', 'tentative', 'tenth',
  'tepee', 'tepees', 'tepid', 'term', 'terms', 'termed',
  'terminal', 'terminals', 'terminate', 'terminates', 'terminated', 'terminology',
  'terrace', 'terraces', 'terrain', 'terrains', 'terrible', 'terribly',
  'terrific', 'terrify', 'terrifies', 'terrified', 'territory', 'territories',
  'terror', 'terrorist', 'terrorists', 'terrorize', 'terrorizes', 'terrorized',
  'terse', 'tertiary', 'test', 'tests', 'tested', 'testify',
  'testifies', 'testified', 'testimonial', 'testimonials', 'testimony', 'texture',
  'textures', 'textual', 'than', 'thank', 'thanks', 'thanked',
  'that', 'the', 'theater', 'theaters', 'theatrical', 'thee',
  'theft', 'thefts', 'their', 'them', 'theme', 'themes',
  'themselves', 'then', 'theology', 'theological', 'theorist', 'theorists',
  'theorize', 'theorizes', 'theorized', 'theory', 'theories', 'there',
  'thereby', 'therefor', 'therefore', 'therein', 'thereof', 'thereon',
  'thereto', 'thereupon', 'these', 'thesis', 'theses', 'they',
  'thick', 'thickly', 'thickness', 'thief', 'thieves', 'thigh',
  'thighs', 'thimble', 'thimbles', 'thin', 'thicker', 'thickest',
  'thickly', 'thickets', 'thickly', 'thickly', 'thickly', 'thickly',
  'thin', 'thinner', 'thinnest', 'thinly', 'third', 'thirds',
  'thirst', 'thirsts', 'thirsted', 'thirsty', 'thirteen', 'thirty',
  'this', 'thither', 'thong', 'thongs', 'thorn', 'thorns',
  'thorough', 'thoroughly', 'those', 'thou', 'though', 'thought',
  'thoughtful', 'thoughtless', 'thousand', 'thousands', 'thread', 'threads',
  'threaded', 'threat', 'threats', 'threaten', 'threatens', 'threatened',
  'three', 'threes', 'threshold', 'thresholds', 'threw', 'thrice',
  'thrift', 'thrifts', 'thrifts', 'thrill', 'thrills', 'thrilled',
  'thriving', 'throat', 'throats', 'throb', 'throbs', 'throbbed',
  'throttle', 'throttles', 'throttled', 'through', 'throughout', 'throw',
  'throws', 'threw', 'thrown', 'thrum', 'thrums', 'thrummed',
  'thrust', 'thrusts', 'thrust', 'thud', 'thuds', 'thudded',
  'thug', 'thugs', 'thumb', 'thumbs', 'thumbprint', 'thumbprints',
  'thump', 'thumps', 'thumped', 'thunder', 'thunders', 'thundered',
  'thunderstorm', 'thunderstorms', 'thursday', 'thus', 'thy', 'thyself',
  'tick', 'ticks', 'ticked', 'ticket', 'tickets', 'ticked',
  'tickle', 'tickles', 'tickled', 'ticklish', 'tidal', 'tidbit',
  'tidbits', 'tide', 'tides', 'tidied', 'tidiness', 'tidings',
  'tidy', 'tidies', 'tidied', 'tie', 'ties', 'tied',
  'tier', 'tiers', 'tiered', 'tiff', 'tiffs', 'tiger',
  'tigers', 'tight', 'tightly', 'tighten', 'tightens', 'tightened',
  'tile', 'tiles', 'tiled', 'tilt', 'tilts', 'tilted',
  'time', 'times', 'timed', 'timeline', 'timelines', 'timely',
  'timer', 'timers', 'timid', 'timing', 'timings', 'tin',
  'tin', 'tinge', 'tinges', 'tinged', 'tingle', 'tingles',
  'tingled', 'tininess', 'tinier', 'tiniest', 'tiny', 'tip',
  'tips', 'tipped', 'tire', 'tires', 'tired', 'tiring',
  'tissue', 'tissues', 'title', 'titles', 'titled', 'titter',
  'titters', 'tittered', 'to', 'toast', 'toasts', 'toasted',
  'toe', 'toes', 'together', 'toilet', 'toilets', 'toil',
  'toils', 'toiled', 'toil', 'toils', 'toiled', 'toil',
  'toils', 'toiled', 'token', 'tokens', 'told', 'tolerable',
  'tolerance', 'tolerances', 'tolerant', 'tolerate', 'tolerates', 'tolerated',
  'toll', 'tolls', 'toll', 'tolls', 'tomato', 'tomatoes',
  'tomb', 'tombs', 'tomorrow', 'tomorrows', 'ton', 'tons',
  'tone', 'tones', 'toned', 'tongue', 'tongues', 'tonight',
  'tonnage', 'tonsils', 'tonsured', 'too', 'took', 'tool',
  'tools', 'tooled', 'tooth', 'toothbrush', 'toothbrushes', 'toothpaste',
  'toothpick', 'toothpicks', 'toothy', 'top', 'tops', 'topped',
  'topper', 'toppers', 'topple', 'topples', 'toppled', 'torment',
  'torments', 'tormented', 'tornado', 'tornadoes', 'torpedo', 'torpedoes',
  'torque', 'torques', 'torque', 'torques', 'torso', 'torsos',
  'tortoise', 'tortoises', 'torture', 'tortures', 'tortured', 'tory',
  'tories', 'toss', 'tosses', 'tossed', 'total', 'totals',
  'totaled', 'totally', 'totem', 'totems', 'totter', 'totters',
  'tottered', 'touch', 'touches', 'touched', 'touching', 'touchy',
  'tough', 'tougher', 'toughest', 'toughness', 'tour', 'tours',
  'toured', 'tout', 'touts', 'touted', 'tow', 'tows',
  'towed', 'towel', 'towels', 'toweled', 'tower', 'towers',
  'towered', 'town', 'towns', 'townhouse', 'townhouses', 'township',
  'townships', 'toy', 'toys', 'toyed', 'trace', 'traces',
  'traced', 'track', 'tracks', 'tracked', 'tract', 'tracts',
  'tractor', 'tractors', 'trade', 'trades', 'traded', 'trademark',
  'trademarks', 'trader', 'traders', 'trading', 'tradition', 'traditions',
  'traditional', 'traditionally', 'traffic', 'trail', 'trails', 'trailed',
  'train', 'trains', 'trained', 'trait', 'traits', 'traitor',
  'traitors', 'trash', 'trashes', 'trashed', 'trauma', 'traumas',
  'travel', 'travels', 'traveled', 'traveller', 'travellers', 'treachery',
  'treacle', 'tread', 'treads', 'trod', 'treacle', 'treacle', 'treacle',
  'treacle', 'treacle', 'treacle', 'treacle', 'treacle', 'treacle',
  'treacle', 'treacle', 'treacle', 'treacle', 'treacle', 'treacle',
  'treacle', 'treacle', 'treacle', 'treacle', 'treacle', 'treacle',
  'treacle', 'treacle', 'treacle', 'treacle', 'treacle', 'treacle',
]);

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/https?:\/\/[\w\./-]+/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
}

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

interface TFIDFModel {
  tfidf: number[][];
}

export function buildTFIDF(postBodies: string[]): TFIDFModel {
  const tokenized = postBodies.map(tokenize);

  const idf = new Map<string, number>();
  const vocab = new Set<string>();

  for (const tokens of tokenized) {
    for (const w of new Set(tokens)) {
      vocab.add(w);
      idf.set(w, (idf.get(w) || 0) + 1);
    }
  }

  const vocabArr = Array.from(vocab);
  const N = postBodies.length;

  const tfidf: number[][] = [];
  for (const tokens of tokenized) {
    const tf = new Map<string, number>();
    for (const w of tokens) {
      tf.set(w, (tf.get(w) || 0) + 1);
    }
    const row = vocabArr.map((w) => (tf.get(w) || 0) * Math.log(N / (idf.get(w) || 1)));
    tfidf.push(row);
  }

  return { tfidf };
}

export function getRelatedPosts(
  currentPost: CollectionEntry<'blog'>,
  allPosts: CollectionEntry<'blog'>[],
  model: TFIDFModel,
  limit = 3,
): CollectionEntry<'blog'>[] {
  const currentIdx = allPosts.findIndex((p) => p.id === currentPost.id);
  if (currentIdx === -1) return [];

  const similarities = allPosts
    .map((p, i) => ({ post: p, score: cosineSimilarity(model.tfidf[currentIdx], model.tfidf[i]) }))
    .filter((s) => s.post.id !== currentPost.id)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  return similarities.map((s) => s.post);
}
